# Netlify configuration for TradeNest
[build]
  command = "npm run build"
  publish = ".next"

# Netlify Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_STANDALONE = "true"

# Scheduled functions (cron jobs)
# Run daily at 9 AM Malaysia Time (1 AM UTC)
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"
  
# Scheduled Functions Configuration
# Note: Netlify Next.js Runtime supports API Routes but requires external cron for scheduling
# For production, use external cron service like cron-job.org or EasyCron

# For manual cron triggers on Netlify, use:
# https://cron-job.org or similar service to call:
# POST https://your-app.netlify.app/api/gazette/scrape
# GET https://your-app.netlify.app/api/cron/fetch-bnm-rates

# BNM Exchange Rate Fetch (Daily at 9 AM MYT / 1 AM UTC)
# Cron expression: 0 1 * * *
# Target: https://your-app.netlify.app/api/cron/fetch-bnm-rates
