# Netlify configuration for TradeNest
[build]
  command = "npm run build"
  publish = ".next"

# Netlify Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_STANDALONE = "true"

