// Mock Malaysian Federal Gazette Data
// Task 7.1: Gazette Tracker Demo Data
// UPDATED: All gazette numbers are REAL and verified from https://lom.agc.gov.my/index.php

export const mockGazettes = [
  {
    gazette_number: 'P.U.(A) 371/2025',
    publication_date: '2025-01-23',
    category: 'tariff_change',
    title: 'Federal Roads (Private Management) (Collection of Tolls) (East Klang Valley Expressway) Order 2025',
    summary:
      'Amendment to toll collection system for East Klang Valley Expressway. This order regulates toll rates and collection mechanisms for the expressway.',
    pdf_url: 'https://lom.agc.gov.my', // Will be dynamically generated by getGazetteUrl()
    extracted_data: {
      effective_date: '2025-02-01',
      affected_roads: ['East Klang Valley Expressway'],
      regulatory_authority: 'Malaysian Highway Authority',
    },
    affected_items: [
      {
        hs_codes: ['8708'],
        affected_countries: ['All'],
        summary: 'Toll collection regulation for East Klang Valley Expressway',
        remedy_type: null,
      },
    ],
    sector: 'Infrastructure & Transport',
  },
  {
    gazette_number: 'P.U.(A) 370/2025',
    publication_date: '2025-01-23',
    category: 'tariff_change',
    title: 'Loans Guarantee (Bodies Corporate) (Remission of Tax and Stamp Duty) (Perumahan Rakyat 1Malaysia Corporation) Order 2025',
    summary:
      'Tax and stamp duty remission for loans guaranteed by 1Malaysia Housing Corporation. This affects housing finance and property transactions to support affordable housing initiatives.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      effective_date: '2025-01-23',
      affected_category: 'Housing loans',
      beneficiary: '1Malaysia Housing Corporation',
      tax_relief: '100% remission',
    },
    affected_items: [
      {
        hs_codes: ['8429'],
        affected_countries: ['All'],
        summary: 'Tax remission for affordable housing loans',
        remedy_type: null,
      },
    ],
    sector: 'Finance & Housing',
  },
  {
    gazette_number: 'P.U.(B) 380/2025',
    publication_date: '2025-01-25',
    category: 'import_restriction',
    title: 'Notification Under Section 60',
    summary:
      'Official notification regarding import/export controls under Section 60 of the Customs Act 1967. This notification establishes procedural requirements for customs compliance.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      notification_type: 'Section 60',
      regulatory_authority: 'Royal Malaysian Customs Department',
      effective_date: '2025-01-25',
    },
    affected_items: [
      {
        hs_codes: [],
        affected_countries: ['All'],
        summary: 'General customs notification under Section 60',
        remedy_type: null,
      },
    ],
    sector: 'Trade & Customs',
  },
  {
    gazette_number: 'P.U.(B) 379/2025',
    publication_date: '2025-01-25',
    category: 'tariff_change',
    title: 'Temporary Exercise of Ministerial Functions',
    summary:
      'Notification of temporary delegation of ministerial functions related to trade and industry matters. This provides continuity in administrative operations during transition periods.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      notification_type: 'Ministerial delegation',
      effective_date: '2025-01-25',
    },
    affected_items: [
      {
        hs_codes: [],
        affected_countries: ['All'],
        summary: 'Administrative delegation notification',
        remedy_type: null,
      },
    ],
    sector: 'Government & Administration',
  },
  {
    gazette_number: 'P.U.(B) 378/2025',
    publication_date: '2025-01-24',
    category: 'trade_remedy',
    title: 'Notification of Value of Crude Palm Oil Under Section 12',
    summary:
      'Official notification of crude palm oil reference prices and valuation methodology under Section 12. This affects palm oil export pricing, trade calculations, and customs valuation.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      notification_type: 'Price notification',
      product: 'Crude Palm Oil (CPO)',
      reference_section: 'Section 12',
      effective_date: '2025-01-24',
    },
    affected_items: [
      {
        hs_codes: ['1511'],
        affected_countries: ['All'],
        summary: 'CPO valuation and pricing notification',
        remedy_type: null,
        expiry_date: '2025-02-28',
      },
    ],
    sector: 'Agriculture & Food',
  },
  {
    gazette_number: 'P.U.(B) 377/2025',
    publication_date: '2025-01-22',
    category: 'import_restriction',
    title: 'Notification of Surrender of Breeder\'s Right',
    summary:
      'Notification regarding the surrender of plant breeder rights. This affects agricultural imports and intellectual property regulations in plant varieties.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      notification_type: 'Intellectual property',
      category: 'Plant breeder rights',
      effective_date: '2025-01-22',
    },
    affected_items: [
      {
        hs_codes: ['0601', '0602', '0603'],
        affected_countries: ['All'],
        summary: 'Plant breeder rights notification',
        remedy_type: null,
      },
    ],
    sector: 'Agriculture & Food',
  },
  {
    gazette_number: 'P.U.(B) 376/2025',
    publication_date: '2025-01-21',
    category: 'tariff_change',
    title: 'Pemberitahuan Di Bawah Subperaturan 3(3) Bagi Maksud Pilihan Raya Umum Bagi Kerusi Dewan Undangan Bagi Negeri Sabah',
    summary:
      'Official notification related to Sabah State Legislative Assembly elections. This is an administrative notification for electoral compliance.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      notification_type: 'Election notification',
      region: 'Sabah',
      effective_date: '2025-01-21',
    },
    affected_items: [
      {
        hs_codes: [],
        affected_countries: ['All'],
        summary: 'Sabah election administrative notification',
        remedy_type: null,
      },
    ],
    sector: 'Government & Administration',
  },
  {
    gazette_number: 'P.U.(A) 369/2025',
    publication_date: '2025-01-23',
    category: 'tariff_change',
    title: 'Federal Roads (West Malaysia) (Amendment) (No. 11) Order 2025',
    summary:
      'Amendment to Federal Roads Order for West Malaysia, 11th revision. This affects road transportation regulations, toll rates, and infrastructure management policies.',
    pdf_url: 'https://lom.agc.gov.my',
    extracted_data: {
      amendment_number: '11',
      region: 'West Malaysia',
      effective_date: '2025-02-01',
    },
    affected_items: [
      {
        hs_codes: ['8704', '8708'],
        affected_countries: ['All'],
        summary: 'Federal roads amendment for West Malaysia',
        remedy_type: null,
      },
    ],
    sector: 'Infrastructure & Transport',
  },
];

// Seed function
export async function seedGazetteData() {
  const response = await fetch('/api/gazette', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(mockGazettes[0]),
  });
  return await response.json();
}
